### ISSUE TITLE
Syntax highlighting is not ok

### ISSUE THREAD

**Issue by Moooartin** [raynigon/vscode-nginx-formatter#10]
Hi,
I'd like to have a nginx formatter but without loosing a great syntax highlighting.
I use `hangxingliu.vscode-nginx-conf-hint` for syntax highlighting and it's perfect, but it cannot work with your formatter...

Is it possible to for you to use this one instead of `william-voyek.vscode-nginx` which is not a great syntax highlighting ?

And also `hangxingliu.vscode-nginx-conf-hint` provides hints as you type.

Thank you

**Comment by raynigon** [comment]
im currently a little bit busy, but i`ll take a look in the next few days :)

**Comment by raynigon** [comment]
I`ll create a new release in the next few days.
