### ISSUE TITLE
Syntax Highlighting Errors

### ISSUE THREAD

**Issue by SorinGFS** [raynigon/vscode-nginx-formatter#227]
The purpose of using a formatter is to bring clarity, but this extension brings max confusion!

the following sample code will produce the result shown in the picture:

```
# regex formatting in both, map and location are full of bugs, I give 2 examples but the list can be loooong!
location ~* (?:#.*#|\.(?:bak|conf|dist|fla|in[ci]|log|orig|psd|sh|sql|sw[op])|^~.*)$ {
    deny all;
}

map $http_name $http_value {
    ~*^(www\.)?domain\.com:.* 1;
    default 0;
}

map $http_name $http_value {
    7d789ac019786442253db411b8e77632 1;  # value not recognized as a number
    ee2f1840417818a254ae94256b0eb8f3 22;  # key not recognized as hex number
    3kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk 33; # key wrongfully recognized as number
    default 44;
}

server {
    location / {
        # wrong format for names as directives despite the fact that they are not in the first position
        include includes/location/dummy/map/dummy/geo/dummy/server/dummy/if/dummy/break/so.on
        # directives not recognized
        rewrite ^/api/(.*)$ /$1 break;
    }
}
```

![Untitled](https://user-images.githubusercontent.com/25417015/163081443-b1f1dbf9-5141-4016-9f6e-b5b405507731.png)

**Comment by raynigon** [comment]
**Please remember to follow the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) when creating issues.**

Please provide specific details on your issues and split the bugs to multiple issues if necessary.
This extension does not provide Syntax Highliting.
Syntax Highliting is provided by https://marketplace.visualstudio.com/items?itemName=ahmadalli.vscode-nginx-conf
Please create an issue [here](https://github.com/ahmadalli/vscode-nginx-conf/issues/new)

If you also have Formatting issues, you can create Issues and PRs in the [nginxbeautifier repository](https://github.com/vasilevich/nginxbeautifier). Currently nginxbeautifier is used for formatting.
This extension is only a wrapper around the library.

**Comment by raynigon** [comment]
Since this seems to be an issue of another extension, the issue will be closed.

**Comment by SorinGFS** [comment]
> seems to be an issue of another extension

This is not an issue of another extension, I tested on a fresh vscode install with only nightOwl theme extension. Any curios can take the code snippet and do the same test. 

Oh, if you mean another extension wich this extension depends on... well, that' NOT my problem, as for my concern I only installed your extension! 

As this extension fails to deliver the objectives which would explain its own existance I think you should remove it entirely from the vscode repository.

**Comment by raynigon** [comment]
# Please remember to follow the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) when commenting on issues.

Feel free to report it, at the moment the extension fullfills all my personal needs.
If it does not for you, feel free to uninstall it.
