### ISSUE TITLE
regexp formatting bug

### ISSUE THREAD

**Issue by youryida** [raynigon/vscode-nginx-formatter#4]
when i format this:
```
location ~ ^/\d{3}/ {
    try_files $uri /index.html;
}
```
the result is error:
```
location ~ ^/\d;
```
thanks!

and,the version is 0.0.4

**Comment by raynigon** [comment]
Hi @youryida ,
thank you for this Feedback, currently im waiting for this to be implemented in the library i`m using.
Eventually this will take some time.

**Comment by raynigon** [comment]
Hi @youryida ,

this is what the developer of the lib i used wrote me:
> I just tested that configuration on `nginx/1.14.0 (Ubuntu)` and it results in an error:
>
>```
>nginx: [emerg] unknown directive "3}/"
>```
>
>So in this case the parser is doing the right thing and trying to parse the brackets normally. The real nginx parser is aware of all valid directives hence the failure. This library only parses and does not validate, and it will try to assume the configuration is valid and print what it can, hence the truncated location.
>
>Basically your user's configuration is using an incorrect syntax, and s/he probably needs to quote the regular expression.

So please check your config and quote the regex.
